### PR TITLE
Linux support

### LINKED ISSUE #11: Question - open to support swift on linux with this?
I was looking around at promise style libraries to help solve a problem in another project, and wanted to utilize this library. It's pretty close, but doesn't currently easily (and consistently) support swift on linux out of the box. I'm willing to make some tweaks and updates to enable that, but wanted to inquire first if that would be acceptable.

I've offered a partial (small) update to Package.swift in #10 - but I'd like to take it a bit further based on my initial exploration:
- [x] update the tests to push them slightly lower (into a subdirectory) to more easily exclude the Host IOS app
- [x] add `swift test` to macOS command line to validate that continues to work as expected (not just through `xcodebuild`)
- [x] add linux focused CI running the tests (in either .travis or .github actions, if you have a preference)
- [x] replace the arc4random usage in the test extensions with a more platform neutral https://developer.apple.com/documentation/swift/randomnumbergenerator

### PR DESCRIPTION
**Pull request by heckj**
resolves #11

### CODE REVIEW

**Comment by heckj** [comment]
I couldn't vet the linux CI without some tweaking, so I saved that for last, will temp enable it on branches, but I vetted the code with:

    swift test # checkin' mac local
    brew install iainsmith/formulae/swift-docker # handy tool
    swift docker test --args --enable-test-discovery # checkin' linux w/ swift 5.2

**Comment by kean** [comment]
Let me wrangle with CI later, I'm having some issues with GitHub integration.

Are you planning to do any additional changes or is it ready to be merged?

**Comment by heckj** [comment]
CI aside, that should be ready to roll - and I'm happy to rebase and squash this all if that would be easier for you.

**Comment by kean** [comment]
That's fine, let me do some testing later today before I merge it. Thanks for putting this together.

**Comment by kean** [comment]
@heckj, I [updated](https://github.com/kean/Future/pull/13) the .travis.yml file. You can't use `matrix` in the kind of setup that I have, so I changed it a bit. I see that the tests on Linux have finished successfully https://travis-ci.org/github/kean/Future/builds/680205461 👍

**Comment by heckj** [comment]
That's fantastic! I'm excited to see that running in CI for this project, and with that - I'm going to turn around and take a stab at using your awesome work within another project (ref https://github.com/SwiftDocOrg/DocTest/issues/1) where it needs some synchronization support while running on Linux.

**Pull request merged**
